import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { CliPlugin } from '@modern-js/app-tools'
import packageJson from '../../package.json'

const versionGen = (): CliPlugin => ({
  name: 'version-gen',

  setup() {
    const { version } = packageJson
    // 自动生成 @/src/utils/version.ts 文件
    const versionFilePath = resolve(__dirname, '../../src/utils/version.ts')
    writeFileSync(
      versionFilePath,
      `// This File Is Generated By Modern CLI Automatically. Please Don't Edit This File.\nconst VERSION = '${version}'\nexport default VERSION\n`,
      { encoding: 'utf-8' },
    )
  },
})

export default versionGen
